apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-stg
  namespace: kube-system
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: n.haoyuan@gmail.com
    privateKeySecretRef:
      name: letsencrypt-stg
    http01: {}
